name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Verificar o repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'  # ou qualquer versão mais recente necessária

    # Instalar dependências
    - name: Install dependencies
      run: npm install

    # Fazer o build
    - name: Build project
      run: npm run build

    # Conectar via SSH e fazer o deploy
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        VPS_USER: hiago
        VPS_HOST: 62.72.9.87
      run: |
        ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $VPS_USER@$VPS_HOST << 'EOF'
          cd /home/hiago/sites/blog.hiagobriano.online
          git pull origin main
          npm install
          npm run build
          pm2 delete blog-next || true
          pm2 start npm --name "blog-next" -- start
          pm2 save
        EOF
